## What is Data Analysis

Data Analysis is the process of collecting, cleaning, organizing data and coming with a conclusion.

# 1.Load the data


In [2]:
import pandas as pd

df = pd.read_excel("data.xlsx")
df.head()

,Unnamed: 0.1,Unnamed: 0,brand,name,price,spec_rating,processor,CPU,Ram,Ram_type,ROM,ROM_type,GPU,display_size,resolution_width,resolution_height,OS,warranty
0,0,0,HP,Victus 15-fb0157AX Gaming Laptop,49900,73.000000,5th Gen AMD Ryzen 5 5600H,"Hexa Core, 12 Threads",8GB,DDR4,512GB,SSD,4GB AMD Radeon RX 6500M,15.6,1920,1080,Windows 11 OS,1
1,1,1,HP,15s-fq5007TU Laptop,39900,60.000000,12th Gen Intel Core i3 1215U,"Hexa Core (2P + 4E), 8 Threads",8GB,DDR4,512GB,SSD,Intel UHD Graphics,15.6,1920,1080,Windows 11 OS,1
2,2,2,Acer,One 14 Z8-415 Laptop,26990,69.323529,11th Gen Intel Core i3 1115G4,"Dual Core, 4 Threads",8GB,DDR4,512GB,SSD,Intel Iris Xe Graphics,14.0,1920,1080,Windows 11 OS,1
3,3,3,Lenovo,Yoga Slim 6 14IAP8 82WU0095IN Laptop,59729,66.000000,12th Gen Intel Core i5 1240P,"12 Cores (4P + 8E), 16 Threads",16GB,LPDDR5,512GB,SSD,Intel Integrated Iris Xe,14.0,2240,1400,Windows 11 OS,1
4,4,4,Apple,MacBook Air 2020 MGND3HN Laptop,69990,69.323529,Apple M1,Octa Core (4P + 4E),8GB,DDR4,256GB,SSD,Apple M1 Integrated Graphics,13.3,2560,1600,Mac OS,1


2. Get Mean, Median and Mode


In [ ]:
var = df['price']
print(var.mean())


np.float64(79907.4098544233)

1. Array Creation using Numpy 



In [3]:
import numpy as np 
arr = np.array([1,2,3,4,5,6,7,9])
print(arr)

[1 2 3 4 5 6 7 9]


2. Create 2D, 3D Using Numpy.


In [5]:
import numpy as np

a = np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


3. Array addition, Substration, Multiplication


In [6]:
a = np.array([1,2,3,4,5,6,7])
b = np.array([1,2,3,4,5,6,7])
print(a+b)
print(a*b)
print(a-b)

[ 2  4  6  8 10 12 14]
[ 1  4  9 16 25 36 49]
[0 0 0 0 0 0 0]
